spring:
  profiles:
    include:
      oauth, real-db
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type:
      jdbc



# Logs
logging:
  level:
    root:
      info


# CORS
cors:
  allow:
    origin: http://localhost:3000

